apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-installer
  labels:
    app: node-installer
spec:
  selector:
    matchLabels:
      app: node-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-installer
    spec:
      hostPID: true
      volumes:
        - name: node-root
          hostPath:
            path: /
        - name: entrypoint
          configMap:
            name: entrypoint
            defaultMode: 0744
      initContainers:
        - image: ghcr.io/spinkube/containerd-shim-spin/node-installer:v0.13.1
          name: kwasm-initializer
          env:
            - name: NODE_ROOT
              value: /mnt/node-root
          securityContext:
            privileged: true
          volumeMounts:
            - name: node-root
              mountPath: /mnt/node-root/
      containers:
        - image: k8s.gcr.io/pause:3.1
          name: pause